docs: Update CONTRIBUTING.md
sws2apps/sws2apps-api pull request #748
Opened 2023-11-10 14:24 UTC by Unviray

# Description

The corrections focus on enhancing the `CONTRIBUTING.md` instructions related to Firebase Emulators setup, obtaining the `GOOGLE_CONFIG_BASE64`, and configuring environment variables.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made corresponding changes to the documentation

2023-11-10 14:30 UTC, rhahao requested changes

2023-11-10 15:10 UTC, Unviray commented on .env.example
> +FIRESTORE_EMULATOR_HOST=127.0.0.1:8080
Just to double-check, is it intended to be `FIREBASE_STORAGE_EMULATOR_HOST` specifically, and not `STORAGE_EMULATOR_HOST`?

2023-11-10 15:10 UTC, Unviray commented on CONTRIBUTING.md
>  - FIRESTORE_EMULATOR_HOST: the `Host:Port` for Firestore Emulator.
Just to double-check, is it intended to be `FIREBASE_STORAGE_EMULATOR_HOST` specifically, and not `STORAGE_EMULATOR_HOST`?

2023-11-10 15:17 UTC, rhahao commented on .env.example
> +FIRESTORE_EMULATOR_HOST=127.0.0.1:8080
Unfortunately, we have to prefix it with `FIREBASE_` per Firebase Docs: https://firebase.google.com/docs/emulator-suite/connect_storage#admin_sdks 😁

2023-11-10 15:17 UTC, rhahao commented on CONTRIBUTING.md
>  - FIRESTORE_EMULATOR_HOST: the `Host:Port` for Firestore Emulator.
Unfortunately, we have to prefix it with `FIREBASE_` per Firebase Docs: https://firebase.google.com/docs/emulator-suite/connect_storage#admin_sdks 😁

2023-11-10 15:21 UTC, rhahao approved these changes

2023-11-10 15:23 UTC, merged

2023-11-29 13:31 UTC, rhahao commented
:tada: This PR is included in version 2.81.0 :tada:

The release is available on [GitHub release](https://github.com/sws2apps/sws2apps-api/releases/tag/v2.81.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: